import type { Metadata } from 'next';
import '../styles/globals.css';
import GlobalLayout from '@/components/common/organisms/GlobalLayout';
import { w95fa } from '../../public/font/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={w95fa.className}>
        <GlobalLayout>{children}</GlobalLayout>
        <div id='portal-root' />
      </body>
    </html>
  );
}
